### ISSUE TITLE
Chat Colours not working

### ISSUE THREAD

**Issue by Wild1145** [Pravian/BukkitLib#8]
For some reason the colorize functionality is no longer working on events at least. The error is as follows:

>[15:28:32] [Server thread/ERROR]: [DarthCraft] Unknown command error: null
[15:28:32] [Server thread/ERROR]: [DarthCraft] java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:210)
	at net.pravian.bukkitlib.util.ChatUtils.colorize(ChatUtils.java:50)
	at net.darthcraft.dcmod.commands.Command_darthcraft.run(Command_darthcraft.java:62)
	at net.darthcraft.dcmod.DarthCraft.onCommand(DarthCraft.java:265)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wild1145** [comment]
It appears that this is something else, not linked to the chat colours.
